name: 'setup the node with cache'
description: 'checkout the code , setup the node js and cache the npm dependencies'

inputs:
  node-version:
    description: node.js version to use
    required: false
    default: '24'
runs:
 using: 'composite'
 steps:
   - name: steup node
     uses: actions/setup-node@v4
     with:
       node-version: ${{inputs.node-version}} 

   - name: npm cache
     uses: actions/cache@v4
     with:
       path: ./npm
       key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
          ${{ runner.os }}-node- 

   - name: Install dependencies
     shell: bash
     run: npm ci           