name: 01 - Building Blocks
on:  | 
  - workflow_dispatch
  - push
jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      name: Say Hello
      run: echo "Hello"

  echo_goodbye:
    runs-on: ubunutu-latest
    steps:
      name: Say Goodbye
      run: echo "goodbye"    


  