name: 02-workflow-events
on: [push, workflow_dispatch, pull_request]
jobs:
  on_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "push"
          echo "github triggers :${{github.event_name}}"