name: 09- Using functions
on: [pull_request, workflow_dispatch]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: PR Title
        run: echo ${{github.event.pull_request.titles}}

      - name: PR label
        run: echo ${{github.event.pull_request.labels}}  
        
      - name: sleep for 20 seconds 
        run: sleep 20  

      - name: failing code
        run: exit 1

      - name: I will be skipped
        if: success()
        run: echo " this step will be printed if the previous step is executed successfully "

      - name: I will execute
        if: failure()
        run: echo "this step will be executed if any previous step is failed"

      - name: I will execute
        if: always()
        run: echo "I will always print, except when the workflow is cancelled."   

      - name: I will execute when cancelled
        if: cancelled() 
        run: echo "I will execute only when the workflow has been cancelled."    