name: node_install_using_docker
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: npm ci
      - run: npm run build --if-present
