name: service-container-db
on: workflow_dispatch
jobs:
  test-with-db:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: code_checkout 
        uses: actions/checkout@v4      

      - name: Wait for Postgres to be ready
        run: |
              until pg_isready -h localhost -p 5432 -U testuser; do
                echo "Waiting for postgres..."
                sleep 2
              done 

      - name: Verify connection with psql
        env:
          PGPASSWORD: testpass
        run: |
            sudo apt-get install -y postgresql-client
            psql -h localhost -U testuser -d testdb -c "SELECT version();"     
          
